task_categorizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.TaskListView.as_view(), name="list"),
    path('completed/', views.CompletedTaskListView.as_view(), name="completed-list"),
    path('answer/<int:task_id>/', views.AnswerView.as_view(), name="answer"),
]

tasks/models.py
from django.db import models


class Mode(models.TextChoices):
    """ファイルシステムへの影響"""
    READ_ONLY = 'R', "Read only"
    WRITABLE = 'W', "Writable"
    UNKNOWN = 'U', 'Either can be read-only or write'


class NotReplaceableReason(models.TextChoices):
    """置き換え不可能な理由"""
    NOT_SUPPORTED = 'NS', 'サポートしていない操作である'
    TOO_COMPLICATE = 'TC', '複雑になりすぎる'
    CANNOT_JUDGE = 'CJ', '判断できない'
    COMPATIBILITY = 'C', '互換性のため'
    BUG = 'B', 'モジュールがバグを含むため'
    NO_CHOICE = 'NC', '---'


class Category(models.Model):
    """そのタスクの属するカテゴリ"""
    name = models.CharField(verbose_name="カテゴリ名",
                            max_length=255,
                            unique=True)

    def __str__(self):
        return self.name


class Answer(models.Model):
    """分類結果"""

    # そのタスクはファイルシステムへ影響を与えるかどうか
    mode = models.TextField(verbose_name='モード',
                            max_length=1,
                            choices=Mode.choices,
                            default=Mode.READ_ONLY)
    # そのモジュールが置き換え可能かどうか
    replaceable = models.BooleanField(verbose_name='置き換え可能',
                                      default=False)
    # 置き換えることができない理由
    reason = models.TextField(verbose_name="置き換え不可能である理由",
                              max_length=2,
                              choices=NotReplaceableReason.choices,
                              default=NotReplaceableReason.NO_CHOICE)
    # 客観的に見てわかりやすい事例であればTrue
    clearly = models.BooleanField(verbose_name='わかりやすい', default=False)
    # 代替可能モジュールの名称
    alternate_module = models.CharField(verbose_name="代替可能モジュール",
                                        max_length=30,
                                        default=None,
                                        blank=True,
                                        null=True)
    message = models.TextField(verbose_name='備考', default="", blank=True)
    task = models.OneToOneField('Task',
                                on_delete=models.CASCADE,
                                null=True,
                                blank=True,
                                related_name='answer')
    # そのタスクが属するカテゴリ
    category = models.ForeignKey('Category',
                                 on_delete=models.SET_NULL,
                                 related_name='answers',
                                 null=True,
                                 blank=True)

    def __str__(self):
        return f"{self.task_id} - {self.message[:15]}"


class AnsibleModule(models.TextChoices):
    """モジュールの選択肢"""
    COMMAND = 'C', 'command'
    SCRIPT = 'SC', 'script'
    RAW = 'R', 'raw'
    SHELL = 'SH', 'shell'


class YamlFile(models.Model):
    """各タスクを記述しているYAMLファイル"""

    path = models.CharField(verbose_name='ファイルパス', max_length=255)
    content = models.TextField(verbose_name='コンテンツ')

    def __str__(self):
        return self.path


class RoleVersion(models.Model):
    """各ロールのバージョン"""

    name = models.CharField(verbose_name='バージョン名', max_length=255)
    min_ansible_version = models.CharField(verbose_name='最小Ansibleバージョン', max_length=10)
    published_at = models.DateTimeField(verbose_name='公開日')
    role = models.ForeignKey('Role',
                             on_delete=models.CASCADE,
                             related_name='versions')

    def __str__(self):
        return f"{self.role}-{self.name}"


class Role(models.Model):
    """ロールのメタデータ"""

    name = models.CharField(verbose_name='ロール名', max_length=255)
    owner = models.CharField(verbose_name='ユーザ', max_length=255)
    repository = models.URLField(verbose_name='リポジトリ')

    def __str__(self):
        return f"{self.owner}.{self.name}"


class Task(models.Model):
    """各バージョンがもつタスク"""

    name = models.CharField(verbose_name="name", max_length=255)
    module = models.CharField(max_length=2,
                              verbose_name='module',
                              choices=AnsibleModule.choices,
                              default=AnsibleModule.COMMAND)
    script = models.TextField(verbose_name="script")
    role_version = models.ForeignKey('RoleVersion',
                                     on_delete=models.CASCADE,
                                     related_name='tasks')
    yaml = models.ForeignKey('YamlFile',
                             on_delete=models.CASCADE,
                             related_name='tasks')
    raw = models.TextField(verbose_name='Raw task')

    def __str__(self):
        return f"{self.script}"

tasks/forms.py
from django import forms
from django.contrib import messages

from .models import Answer, NotReplaceableReason


class AnswerPostForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = [
            'mode', 'replaceable', 'clearly', 'message', 'task', 'reason', 'category', 'alternate_module'
        ]

    def __init__(self, *args, **kwargs):
        super(AnswerPostForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            if isinstance(field.widget, forms.Textarea):
                field.widget.attrs["rows"] = 1
            if isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = "custom-control-input"
            if isinstance(field.widget, forms.Select):
                field.widget.attrs['class'] = "custom-select"
        self.fields['task'].widget = forms.HiddenInput()

    def set_task(self, task_id: int):
        if task_id is None:
            raise AttributeError("Task IDが指定されていません")
        self.fields['task'].initial = task_id

    def clean_reason(self):
        reason = self.cleaned_data['reason']
        is_replaceable = self.cleaned_data['replaceable']
        if not is_replaceable and reason == NotReplaceableReason.NO_CHOICE.value:
            self.fields['reason'].widget.attrs['class'] = "custom-select is-invalid"
            self.add_error('reason', forms.ValidationError('置き換え不可能である時はその理由を選択する必要があります．'))
        if is_replaceable and reason != NotReplaceableReason.NO_CHOICE.value:
            self.fields['reason'].widget.attrs['class'] = "custom-select is-invalid"
            self.add_error('reason', forms.ValidationError('置き換え可能な時にこの理由は選択できません．'))
        return reason

    def clean_category(self):
        category = self.cleaned_data['category']
        if category is None:
            self.fields['category'].widget.attrs['class'] = "custom-select is-invalid"
            self.add_error('category', forms.ValidationError('カテゴリが未選択です'))
        return category

    def clean_alternate_module(self):
        mod = self.cleaned_data['alternate_module']
        is_replaceable = self.cleaned_data['replaceable']
        if is_replaceable:
            if mod is None or len(mod) == 0:
                self.fields['alternate_module'].widget.attrs['class'] = "form-control is-invalid"
                self.add_error('alternate_module', forms.ValidationError('代替可能モジュールが未入力です'))
        return mod

tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, FormView
from django.urls import reverse

from .models import Task
from .forms import AnswerPostForm


class TaskListView(LoginRequiredMixin, ListView):
    """未処理のタスク一覧を返す"""

    template_name = 'tasks/task_list.html'
    queryset = Task.objects.filter(answer__isnull=True).order_by('pk')
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(TaskListView, self).get_context_data(object_list=object_list, **kwargs)
        ctx['is_processed'] = False
        return ctx


class CompletedTaskListView(LoginRequiredMixin, ListView):
    """処理済みのタスク一覧を返す"""
    template_name = 'tasks/task_list.html'
    queryset = Task.objects.filter(answer__isnull=False).order_by('pk')
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(CompletedTaskListView, self).get_context_data(object_list=object_list, **kwargs)
        ctx['is_processed'] = True
        return ctx


class AnswerView(LoginRequiredMixin, FormView):

    template_name = 'tasks/answer.html'
    form_class = AnswerPostForm

    def get_next_task(self, current_id):
        """次のタスクを一つ返す"""
        try:
            return Task.objects.order_by('pk').get(pk=current_id+1)
        except:
            return None

    def get_success_url(self, current_id):
        latest_task = self.get_next_task(current_id)
        if latest_task is None:
            return reverse('tasks:list')
        return reverse('tasks:answer', kwargs={'task_id': latest_task.pk})

    def get_context_data(self, **kwargs):
        task = kwargs.pop('task')
        ctx = super(AnswerView, self).get_context_data(**kwargs)
        ctx['item'] = task
        return ctx

    def get(self, request, *args, **kwargs):
        task_id = kwargs.get('task_id', None)
        if task_id is None:
            task = Task.objects.filter(answer__isnull=True).order_by('pk').first()
        else:
            task = Task.objects.get(pk=int(task_id))
        if task is None:
            return redirect('tasks:completed-list')
        try:
            form = AnswerPostForm(instance=task.answer)
        except Exception:
            form = AnswerPostForm()
        form.set_task(task.pk)
        ctx = self.get_context_data(form=form, task=task)
        return self.render_to_response(ctx)

    def form_valid(self, form: 'AnswerPostForm'):
        obj = form.save()
        messages.info(self.request, f"結果を保存しました．Task ID: {obj.task.pk}")
        return redirect(self.get_success_url(obj.task.pk))

    def post(self, request, *args, **kwargs):
        task_id = kwargs.get('task_id')
        task = Task.objects.get(pk=task_id)
        try:
            answer_form = AnswerPostForm(request.POST, instance=task.answer)
        except Exception:
            answer_form = AnswerPostForm(request.POST)
        if answer_form.is_valid():
            return self.form_valid(answer_form)
        messages.error(request, f'バリデーションエラーです')
        ctx = self.get_context_data(form=answer_form, task=task)
        return self.render_to_response(ctx)

tasks/templates/tasks/answer.html
{% extends 'base.html' %}

{% block title %}回答{% endblock %}

{% block content %}
    <div class="col-xl-7 col-md-6 col-sm-12" style="margin-top: 1rem;">
        <div class="card">
            <div class="card-header">タスクの情報</div>
            <div class="card-body">
                <h5>{{ item.name }}</h5>
                <pre class="prettyprint linenums lang-yaml">{{ item.raw|linebreaksbr }}</pre>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">ロール名：{{ item.role_version.role.owner }}.{{ item.role_version.role.name }}</li>
                    <li class="list-group-item">リポジトリ：{{ item.role_version.role.repository|urlize }}</li>
                    <li class="list-group-item">バージョン：{{ item.role_version.name }}</li>
                </ul>
                <p style="margin-top: 1rem;">
                    <button type="button" class="btn btn-outline-primary" data-toggle="collapse" data-target="#wholeYaml" aria-expanded="false" aria-controls="wholeYaml">
                        このタスクを含むYAML全体を表示する
                    </button>
                </p>
                <div class="collapse" id="wholeYaml">
                    <h5>{{ item.yaml.path }}</h5>
                    <pre class="prettyprint linenums lang-yaml">{{ item.yaml.content|linebreaksbr }}</pre>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-5 col-md-6 col-sm-12" style="margin-top: 1rem; margin-bottom: 1rem;">
        <div class="card">
            <div class="card-header">
                入力
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'tasks:answer' item.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ form.mode.id_for_label }}">{{ form.mode.label }}</label>
                            </div>
                            {{ form.mode }}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
                            </div>
                            {{ form.category }}
                            {% if form.category.errors %}<div class="invalid-feedback">{{ form.category.errors|join:', ' }}</div>{% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <div class="custom-control custom-switch">
                                {{ form.replaceable }}
                                <label class="custom-control-label" for="{{ form.replaceable.id_for_label }}">{{ form.replaceable.label }}</label>
                            </div>
                        </div>
                        <div class="input-group mb-3" id="reason_selector">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ form.reason.id_for_label }}">{{ form.reason.label }}</label>
                            </div>
                            {{ form.reason }}
                            {% if form.reason.errors %}<div class="invalid-feedback">{{ form.reason.errors|join:', ' }}</div>{% endif %}
                        </div>
                        <div class="input-group mb-3" id="module_box">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ form.alternate_module.id_for_label }}">{{ form.alternate_module.label }}</label>
                            </div>
                            {{ form.alternate_module }}
                            {% if form.alternate_module.errors %}<div class="invalid-feedback">{{ form.alternate_module.errors|join:', ' }}</div>{% endif %}
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ form.message.id_for_label }}">{{ form.message.label }}</label>
                            </div>
                            {{ form.message }}
                        </div>
                    </div>
                    {{ form.task }}
                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            {{ form.clearly }}
                            <label class="custom-control-label" for="{{ form.clearly.id_for_label }}">{{ form.clearly.label }}</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" style="margin-top: 1rem; ">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block additional_script %}
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?lang=yaml&skin=desert"></script>
    <script type="application/javascript">
        const isReplaceable = document.getElementById('id_replaceable');
        const reason = document.getElementById('id_reason');
        const altModule = document.getElementById('id_alternate_module');
        const moduleBox = document.getElementById('module_box');
        const reasonBox = document.getElementById('reason_selector');
        let selectedReason = reason.value;
        let selectedModule = altModule.value;
        function toggle(isEnabled) {
            reasonBox.hidden = isEnabled;
            moduleBox.hidden = !isEnabled;
            if (isEnabled) {
                altModule.value = selectedModule;
                selectedReason = reason.value;
                reason.value = 'NC';
            } else {
                selectedModule = altModule.value;
                altModule.value = '';
                reason.value = selectedReason;
            }
        }
        toggle(isReplaceable.checked);
        isReplaceable.addEventListener('change', (e) => {
            toggle(e.target.checked)
        });
    </script>
    <style>
        .prettyprint ol.linenums > li { list-style-type: decimal !important; }
        .prettyprint {
            padding: 10px;
        }
    </style>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block title %}{% if is_processed %}処理済み{% else %}未処理{% endif %}タスク一覧{% endblock %}

{% block content %}
    <div class="col-xl-10 offset-xl-1">
        <div class="card">
            <div class="card-header">
                <h2>{% if is_processed %}処理済み{% else %}未処理{% endif %}タスク一覧</h2>
            </div>
            <div class="card-body">
                {% if task_list|length > 0 %}
                    <table class="table table-striped">
                        <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>モジュール</th>
                            <th>スクリプト</th>
                            <th>タスク名</th>
                            <th>回答済み</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in task_list %}
                            <tr>
                                <td><a style="display: block;" href="{% url 'tasks:answer' item.pk %}">{{ item.pk }}</a></td>
                                <td>{{ item.get_module_display }}</td>
                                <td>{{ item.script|truncatechars:20 }}</td>
                                <td>{{ item.name|truncatechars:20 }}</td>
                                <td><input type="checkbox" disabled="disabled" {% if item.answer %}checked{% endif %}></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No items are left.</p>
                    <p>See <a href="{% url 'tasks:completed-list' %}">completed tasks</a>.</p>
                {% endif %}
            <nav aria-label="Page navigation" class="d-flex justify-content-center">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&lt;</span>
                    </a>
                  </li>
                  {% endif %}

                  {% if page_obj.number > 3 %}
                  <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">1</a>
                  </li>
                  {% endif %}

                  {% if page_obj.number > 4 %}
                  <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
                  {% endif %}

                  {% for link_page in page_obj.paginator.page_range %}
                  {% if link_page == page_obj.number %}
                  <li class="page-item active">
                    <a class="page-link" href="?page={{ link_page }}">
                      {{ link_page }}
                    </a>
                  </li>
                  {% elif link_page < page_obj.number|add:3 and link_page > page_obj.number|add:-3 %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ link_page }}">
                      {{ link_page }}
                    </a>
                  </li>
                  {% endif %}
                  {% endfor %}

                  {% if page_obj.number < page_obj.paginator.num_pages|add:-3 %}
                  <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
                  {% endif %}

                  {% if page_obj.number < page_obj.paginator.num_pages|add:-2 %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">{{ page_obj.paginator.num_pages}}</a>
                  </li>
                  {% endif%}

                  {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&gt;</span>
                    </a>
                  </li>
                  {% endif %}
                </ul>
            </nav>
            </div>
        </div>
    </div>
{% endblock %}