accounts/urls.py
import logging

from typing import TYPE_CHECKING

from django.urls import path
from django.contrib.auth import views as auth_views

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

task_categorizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.TaskListView.as_view(), name="list"),
    path('completed/', views.CompletedTaskListView.as_view(), name="completed-list"),
    path('answer/<int:task_id>/', views.AnswerView.as_view(), name="answer"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block additional_header %}{% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    <div class="container" style="margin-top:1rem;">
        {% include 'messages.html' %}
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block additional_script %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}分類タスク{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-xl-8 offset-xl-2">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-danger">ログアウト</button></a>
            {% else %}
                <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-primary">ログイン</button></a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
        {{ message }}
        <button class="close" data-dismiss="alert" aria-label="Close" type="button">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-md  navbar-light bg-light">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navi" aria-controls="navi" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navi">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'tasks:list' %}">処理待ち一覧</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tasks:completed-list' %}">処理済み一覧</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                {% if user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">管理画面</a></li>
                {% endif %}
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a></li>
            {% endif %}
        </ul>
    </div>
</nav>